language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
script:
  #  - npm test -- --coverage # Include coverage when running tests
  - npm test
  - npm run build
  #after_script: # Upload coverage reports
  #  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
